### ISSUE TITLE
Assigning data should cause xMax, xMin, yMax and yMin to be re-calculated

### ISSUE THREAD

**Issue by Planeshifter** [figure-io/polymer-timeseries#1]
When assigning new data to the plot element as in the command 

```
el.data = [ [ [ ... ], [ ... ], ...], [ [ ... ], [ ... ], ...] ]
```

should the  `xMax`, `xMin`, `yMax` and `yMin` properties be re-calculated to make sure that the paths fit on the plot? 

Currently they are re-calculated only when they have not been manually set and are still `null`. Is this the intended behaviour?

**Comment by kgryte** [comment]
This **is** the intended behavior. Once in manual mode, the responsibility to update axes is in userland. This is how Matlab plotting works. 

And now, because of how data binding works (not as straightforward for deep watching) and the current hack requiring data to be reassigned at each update, we have no way _a priori_ of knowing whether an assignment should require axis limits be recalculated or not. 

If a user wants to auto-scale, she can set the limits to `null` before assigning the data.

**Comment by Planeshifter** [comment]
Okay, thanks for clarifying!
